Iss 113
CCBR/CARLISLE pull request #117
Opened 2024-02-08 17:26 UTC by slsevilla

## Changes

- Adds a `--force` flag to allow for re-initialization of a workdir
- Fixes error with `testrun` in DESEQ2
- Decreases the number of samples being run with `testrun`, essentially running `tinytest` as default and removing `tinytest` as an option
- Reads version from `VERSION` file instead of github repo link
- Added a `CHANGELOG`

## Issues

- [ ] fixes #96
- [ ] fixes #97 
- [ ] fixes #112
- [ ] fixes #113 
- [ ] fixes #115
- [ ] fixes #116

## PR Checklist

(~Strikethrough~ any points that are not applicable.)

- [x] This comment contains a description of changes with justifications, with any relevant issues linked.
- [x] Update docs if there are any API changes.
- [x] Update `CHANGELOG.md` with a short description of any user-facing changes and reference the PR number. Guidelines: https://keepachangelog.com/en/1.1.0/

2024-02-08 17:39 UTC, kopardev approved these changes
Everything looks good to me. Also, delete the "test_dev" GHA WF as it refers to some 9999.9999 version which does not exist and include that in this PR.

2024-02-08 17:51 UTC, kelly-sovacool commented
Can you edit the title of this PR to be a short description of the changes?

2024-02-08 18:11 UTC, kelly-sovacool requested changes
`testrun` should be switched to `runtest` in the docs, right?

https://github.com/CCBR/CARLISLE/blob/16a4d7a8f014941c2b73464bd08e0c34de129f58/docs/user-guide/run.md?plain=1#L14-L30

2024-02-08 19:06 UTC, slsevilla commented on CHANGELOG.md
> +
yep - done with 42c8fd5f45bed26c026724cec5343fa8995238b2

2024-02-09 00:12 UTC, kelly-sovacool commented
My test run failed in the GO enrichment rule:

```
Quitting from lines 19-52 [setup] (_go_enrichment.Rmd)
Error in `install.packages()`:
! unable to install packages
Backtrace:
  1. BiocManager::install(new.packages, INSTALL_opts = "--no-lock")
  2. BiocManager:::.install(...)
  3. BiocManager:::.install_repos(...)
  4. BiocManager:::.inet_install.packages(...)
  6. base::tryCatch(...)
  7. base (local) tryCatchList(expr, classes, parentenv, handlers)
  8. base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
  9. value[[3L]](cond)
 10. BiocManager:::.inet_error(e)
Execution halted
```

The good news is all other jobs passed!

2024-02-20 05:11 UTC, slsevilla commented
Finished testing these changes - everything went to completion. ready for you to test again @kelly-sovacool !

2024-02-20 14:57 UTC, kelly-sovacool commented
test run submitted

```sh
bash /data/CCBR_Pipeliner/Pipelines/CARLISLE/carlisle-dev-sovacool/carlisle --runmode=init --workdir=/data/sovacoolkl/carlisle_test_iss-113_2
bash /data/CCBR_Pipeliner/Pipelines/CARLISLE/carlisle-dev-sovacool/carlisle --runmode=runtest --workdir=/data/sovacoolkl/carlisle_test_iss-113_2
```

2024-02-21 20:16 UTC, kelly-sovacool approved these changes
all jobs in my test run completed successfully 🎉

2024-02-21 21:35 UTC, merged