Add new rules visualizing CARLISLE results
CCBR/CARLISLE pull request #132
Opened 2024-05-23 20:42 UTC by epehrsson

## Changes

Adds rules:
- count_peaks - output table with number of peaks per condition, visualize number of peaks and correlation between dedup and no_dedup peaks
- cov_correlation - find Pearson correlation in genome-wide coverage for all samples, plot heatmap and PCA
- homer_enrich - visualize HOMER enrichment over genic features for each condition
- combine_homer - add MACS2 fold change and q-value to HOMER annotation table 

## PR Checklist

- [x ] This comment contains a description of changes with justifications, with any relevant issues linked.
- [ x] Update docs if there are any API changes. - none
- [ x] Update `CHANGELOG.md` with a short description of any user-facing changes and reference the PR number. Guidelines: https://keepachangelog.com/en/1.1.0/

2024-05-29 14:57 UTC, kelly-sovacool commented
Thanks for opening this PR, @epehrsson! Sorry I didn't notice it -- in the future you can tag me with `@kelly-sovacool` somewhere in the this thread to notify me if you want me to review it.

Were you able to run this successfully on biowulf?

2024-05-29 16:17 UTC, epehrsson commented
Hi @kelly-sovacool, sorry for not tagging you! Yes, I could run it on the test data and on two projects I'd processed earlier, which recapitulated the results of the rules. =

2024-05-29 19:42 UTC, kelly-sovacool commented
Thanks for this contribution @epehrsson! I proposed changes [here](https://github.com/CCRGeneticsBranch/CARLISLE/pull/1) so that your new rules will also use the docker container. Please take a look and merge that if it looks good, then we'll run one more test to make sure I didn't break anything before merging this PR into main.

2024-05-30 12:29 UTC, epehrsson commented
Thanks, Kelly! The changes look good, and I completed the pull request.

2024-05-30 19:25 UTC, kelly-sovacool requested changes

2024-05-30 19:25 UTC, kelly-sovacool commented on workflow/rules/annotations.smk
> +        annotation_summary=expand(join(RESULTSDIR,"peaks","{{qthresholds}}","{{peak_caller}}","annotation","homer","{treatment_control_list}.{{dupstatus}}.{{peak_caller_type}}.annotation.summary"),tr
```suggestion

def get_annotation_files(wildcards):
    """
    treatment_control_list depends on the peak caller
    """
    return expand(join(RESULTSDIR,"peaks", wildcards.qthresholds, wildcards.peak_caller, "annotation","homer",
           "{treatment_control_list}" + "." + wildcards.dupstatus + "." + wildcards.peak_caller_type + ".annotation.summary"),
           treatment_control_list = TREATMENT_LIST_M if wildcards.peak_caller.startswith('macs2') else TREATMENT_LIST_SG)
    

rule homer_enrich:
    """
    Plot enrichment over genic features
    """
    input: 
        annotation_summary=get_annotation_files
```

2024-06-12 12:40 UTC, merged